leafs: # Group name
  hosts: # Group type
    leaf01: # Host name (ansible_host is a required variable)
      ansible_host: 192.0.2.100
    leaf02:
      ansible_host: 192.0.2.110

spines:
  hosts:
    spine01:
      ansible_host: 192.0.2.120
    spine02:
      ansible_host: 192.0.2.130

network: # Group name
  children: # Group type (children)
    leafs: # Child group
    spines: # Child group

webservers:
  hosts:
    webserver01:
      ansible_host: 192.0.2.140
      http_port: 80 # Custom variable
    webserver02:
      ansible_host: 192.0.2.150
      http_port: 443

datacenter:
  children:
    network:
    webservers:
